// The page's own behaviour, extracted from an inline <script> so the
// Content-Security-Policy can stay strict. An inline block would need
// 'unsafe-inline' or a hash that changes every time the file does, and
// web/_gen/frames.py rewrites index.html, so a hash would go stale on
// its own. Blocking this script kills the whole demo, which is exactly
// what happened on the first deploy.
import { instantiateModemModule, SessionHandle, Role, Duplex, SessionState, STAGE_NAMES } from './session.js';
import { ModemEndpoint, summariseMicDiagnostics } from './modem.js';
import { WiredEndpoint, decode as decodeWired } from './wired.js';
import {
  ensurePlaybackAudioSession,
  attachSecurityPolicyListener,
  cspViolations,
  AudioDiagnostics,
  computeRms,
  waitForAudibleSignal,
} from './audio-diagnostics.js';

// The single fix most likely to matter on iOS - see audio-diagnostics.js's
// own doc - set as early as the module can run, well before any click.
// Harmless and idempotent to call this early: it only configures a
// category, it does not play anything or need a gesture.
ensurePlaybackAudioSession();
attachSecurityPolicyListener();

// ---------------------------------------------------------------------
// The nine performed overture phases the explainer describes. Labels
// match STAGE_NAMES exactly, index for index, so the copy here can never
// silently drift from what the WASM session itself reports.
// ---------------------------------------------------------------------
const PHASES = [
  { label: STAGE_NAMES[0], description: 'The click of the line being seized - a relay closing, not a tone. It is the sound of the call existing at all, a beat before anything is dialled.' },
  { label: STAGE_NAMES[1], description: 'A continuous two-tone signal telling the exchange the line is ready to take a number. The UK pair is 350 and 450 Hz, different from the US pair most film and television dial tone actually is.' },
  { label: STAGE_NAMES[2], description: 'DTMF, the touch-tone digits. Each key sends two frequencies at once, one from a row and one from a column, so the exchange can tell exactly which one was pressed.' },
  { label: STAGE_NAMES[3], description: "The ringing tone you hear while the far end's phone rings, generated by your own exchange rather than the far end's phone. The UK cadence is a double ring: two short bursts of 400 and 450 Hz, then a pause." },
  { label: STAGE_NAMES[4], description: 'The calling indicator. Before anything else happens, the originating modem announces itself on a channel a voice call never touches, so the far end knows straight away that this is a data call.' },
  { label: STAGE_NAMES[5], description: 'The answer tone: 2100 Hz, its phase flipped 180 degrees every 450 milliseconds. Analogue phone networks ran echo suppressors that muted a call whenever it looked like only one side was talking, fine for speech and fatal for two modems talking at once. The phase reversals are a signal those suppressors were built to recognise, and switch themselves off for.' },
  { label: STAGE_NAMES[6], description: 'Call menu and joint menu. The two modems compare what modulations they each support and settle on the one they will actually use.' },
  { label: STAGE_NAMES[7], description: 'The acknowledgement that both ends agreed, followed by a short, deliberate silence: the last quiet moment before the two modems start probing the line itself.' },
  { label: STAGE_NAMES[8], description: "An impression of the real V.34-style probing that follows in an actual call, where two modems measure the line's own noise and frequency response before committing to a speed. There is no physical phone line here to measure, so this stage is texture, not a conformant negotiation - the one stage on this page that is not a faithful reconstruction." },
];

const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

const terminalOutput = document.getElementById('terminal-output');
const nowPlaying = document.getElementById('now-playing');
const overtureBtn = document.getElementById('overture-btn');
const micDiagnostic = document.getElementById('mic-diagnostic');
const canvas = document.getElementById('waterfall');
const phaseListEl = document.getElementById('phase-list');

const soundHelpCheckpoints = document.getElementById('sound-help-checkpoints');
const soundHelpState = document.getElementById('sound-help-state');
const resumeSoundBtn = document.getElementById('resume-sound-btn');
const copyDiagnosticsBtn = document.getElementById('copy-diagnostics-btn');
const copyDiagnosticsStatus = document.getElementById('copy-diagnostics-status');

// -----------------------------------------------------------------------
// Routing: three routes behind one page, plus the plain landing. See the
// "The live routes" section, further down, for the full doc.
// -----------------------------------------------------------------------
const launcher = document.getElementById('launcher');
const launchDemoBtn = document.getElementById('launch-demo-btn');
const launchOriginateBtn = document.getElementById('launch-originate-btn');
const launchReceiveBtn = document.getElementById('launch-receive-btn');
const routeStartBlock = document.getElementById('route-start-block');
const routeStartCopy = document.getElementById('route-start-copy');
const routeStartBtn = document.getElementById('route-start-btn');

const appModeBackBtn = document.getElementById('app-mode-back-btn');
const wiredPanel = document.getElementById('wired-panel');
const wiredPhase = document.getElementById('wired-phase');
const wiredStatusA = document.getElementById('wired-status-a');
const wiredStatusB = document.getElementById('wired-status-b');
const wiredCaptionA = document.getElementById('wired-caption-a');
const wiredCaptionB = document.getElementById('wired-caption-b');
const wiredLogA = document.getElementById('wired-log-a');
const wiredLogB = document.getElementById('wired-log-b');
const wiredCanvas = document.getElementById('wired-waterfall');
const wiredDataCheck = document.getElementById('wired-databcheck');
const wiredDigits = document.getElementById('wired-digits');
const wiredDialBtn = document.getElementById('wired-dial');
const wiredHangupBtn = document.getElementById('wired-hangup');
const wiredStopBtn = document.getElementById('wired-stop');
const wiredSendSide = document.getElementById('wired-send-side');
const wiredChat = document.getElementById('wired-chat');
const wiredSendBtn = document.getElementById('wired-send');

const endpointPanel = document.getElementById('endpoint-panel');
const endpointBackBtn = document.getElementById('endpoint-back-btn');
const endpointHeading = document.getElementById('endpoint-heading');
const endpointIntro = document.getElementById('endpoint-intro');
const shareBlock = document.getElementById('share-block');
const qrCodeEl = document.getElementById('qr-code');
const shareLinkInput = document.getElementById('share-link');
const shareCopyBtn = document.getElementById('share-copy-btn');
const shareCopyStatus = document.getElementById('share-copy-status');
const endpointStatus = document.getElementById('endpoint-status');
const endpointCaption = document.getElementById('endpoint-caption');
const signalIndicators = document.getElementById('signal-indicators');
const micActivityDot = document.getElementById('mic-activity-dot');
const modemSignalDot = document.getElementById('modem-signal-dot');
const endpointDeadline = document.getElementById('endpoint-deadline');
const endpointDataCheck = document.getElementById('endpoint-databcheck');
const endpointHangupBtn = document.getElementById('endpoint-hangup');
const endpointStopBtn = document.getElementById('endpoint-stop');
const chatInput = document.getElementById('chat-input');
const chatSendBtn = document.getElementById('chat-send');
const chatLog = document.getElementById('chat-log');

function appendTerminalLine(container, text, { command = false } = {}) {
  const line = document.createElement('p');
  line.className = 'terminal-line' + (command ? ' terminal-line--command terminal-line--reveal' : ' terminal-line--phase');
  line.textContent = text;
  container.appendChild(line);
  container.scrollTop = container.scrollHeight;
  return line;
}

// -----------------------------------------------------------------------
// The waterfall: frequency up the axis (300-3400 Hz, the whole telephone
// band), time across, newest column at the right - same layout modem-tui's
// own renderer uses, so a visitor recognises this when they later run the
// binary (see brand/README.md and the design spec's "Components" table).
//
// Phosphor decay is read from the brand token, never a fresh guess here -
// the same rule modem-tui/src/waterfall.rs follows for its own decay, and
// for the same reason: it is the strongest CRT cue there is, and the two
// surfaces have to agree on it or they read as different products. Each
// frame the whole canvas is faded by `1 - exp(-dt / decaySeconds)` before
// the new column is drawn, which is the continuous-time form of the same
// exponential the TUI applies per scrolled column.
// -----------------------------------------------------------------------
class Waterfall {
  constructor(canvasEl) {
    this.ctx = canvasEl.getContext('2d');
    this.width = canvasEl.width;
    this.height = canvasEl.height;
    const decayCss = getComputedStyle(document.documentElement).getPropertyValue('--modem-phosphor-decay').trim();
    this.decaySeconds = parseFloat(decayCss) || 2.56;
    const groundCss = getComputedStyle(document.documentElement).getPropertyValue('--modem-ground').trim();
    const greenCss = getComputedStyle(document.documentElement).getPropertyValue('--modem-green-bright').trim();
    this.ground = hexToRgb(groundCss);
    this.bright = hexToRgb(greenCss);
    this.lastFrame = null;
    this.floorDb = -70;
    this.ctx.fillStyle = groundCss;
    this.ctx.fillRect(0, 0, this.width, this.height);
  }

  frame(analyser, sampleRate) {
    const now = performance.now();
    const dt = this.lastFrame === null ? 1 / 60 : (now - this.lastFrame) / 1000;
    this.lastFrame = now;

    const fadeAlpha = 1 - Math.exp(-dt / this.decaySeconds);
    this.ctx.fillStyle = `rgba(${this.ground.r}, ${this.ground.g}, ${this.ground.b}, ${fadeAlpha})`;
    this.ctx.fillRect(0, 0, this.width, this.height);

    // Shift everything one column left, then draw the new column at the
    // right edge - the scrolling half of the effect.
    this.ctx.drawImage(this.ctx.canvas, -1, 0);

    const bins = new Float32Array(analyser.frequencyBinCount);
    analyser.getFloatFrequencyData(bins);
    const hzPerBin = sampleRate / analyser.fftSize;

    for (let y = 0; y < this.height; y++) {
      const freq = 3400 - (y / this.height) * (3400 - 300);
      const bin = Math.min(bins.length - 1, Math.max(0, Math.round(freq / hzPerBin)));
      const db = bins[bin];
      const t = Math.min(1, Math.max(0, (db - this.floorDb) / (0 - this.floorDb)));
      const r = lerp(this.ground.r, this.bright.r, t);
      const g = lerp(this.ground.g, this.bright.g, t);
      const b = lerp(this.ground.b, this.bright.b, t);
      this.ctx.fillStyle = `rgb(${r}, ${g}, ${b})`;
      this.ctx.fillRect(this.width - 1, y, 1, 1);
    }
  }

  reset() {
    this.lastFrame = null;
    this.ctx.fillStyle = `rgb(${this.ground.r}, ${this.ground.g}, ${this.ground.b})`;
    this.ctx.fillRect(0, 0, this.width, this.height);
  }
}

function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return { r: parseInt(h.slice(0, 2), 16), g: parseInt(h.slice(2, 4), 16), b: parseInt(h.slice(4, 6), 16) };
}

function lerp(a, b, t) {
  return Math.round(a + (b - a) * t);
}

const waterfall = new Waterfall(canvas);
// The "one device" live demo's own waterfall, driven off WiredEndpoint's
// analyser tap (see wired.js's own doc on why that tap exists) rather
// than the prerendered buffer this one reads from - the wired call is
// live audio with no buffer to slice. Kept as a second Waterfall
// instance, not a shared one: the two demos can be mid-animation at
// once (nothing stops a visitor opening "one device" without having
// pressed Dial first), and each owns its own canvas and fade state.
const wiredWaterfall = new Waterfall(wiredCanvas);
let wiredWaterfallRaf = null;

function startWiredWaterfall(endpoint) {
  stopWiredWaterfall();
  const draw = () => {
    try {
      wiredWaterfall.frame(endpoint.analyser, endpoint.ctx.sampleRate);
    } catch (err) {
      console.error('wired waterfall draw failed', err);
      return;
    }
    wiredWaterfallRaf = requestAnimationFrame(draw);
  };
  wiredWaterfallRaf = requestAnimationFrame(draw);
}

function stopWiredWaterfall() {
  if (wiredWaterfallRaf !== null) {
    cancelAnimationFrame(wiredWaterfallRaf);
    wiredWaterfallRaf = null;
  }
  wiredWaterfall.reset();
}

// -----------------------------------------------------------------------
// Prerendering the overture: the same modem-wasm build the real endpoint
// uses, run once on the main thread (no AudioWorklet needed for this -
// nothing here is on a real-time deadline) to render the whole
// performance into one buffer, segmented by the stage that owns each
// sample. Playing back a slice of that one real rendering is what makes
// "each phase individually playable" actually play the genuine DSP
// output rather than a second, hand-rolled tone generator that could
// drift from it.
// -----------------------------------------------------------------------
let audioCtx = null;
let prerenderPromise = null;
// The overture's own diagnostics - lighter than wired.js/modem.js's
// (there is no separate worklet fetch/module for it to check in on: the
// prerender runs on the main thread), but state history and resume
// errors are just as real here as anywhere else audio gets played.
const overtureDiagnostics = new AudioDiagnostics('overture');

// Safari (desktop and every iOS browser - Apple requires all of them to
// run WebKit) still ships this prefixed on some versions.
const AudioContextCtor = window.AudioContext || window.webkitAudioContext;

function ensureAudioContext() {
  if (!audioCtx) {
    if (!AudioContextCtor) {
      throw new Error('this browser exposes no AudioContext (or webkitAudioContext) at all');
    }
    ensurePlaybackAudioSession();
    audioCtx = new AudioContextCtor();
    overtureDiagnostics.recordState(audioCtx);
  }
  if (audioCtx.state === 'suspended' || audioCtx.state === 'interrupted') {
    // Fired synchronously here, on first use - see this function's own
    // callers, every one of which is the first statement evaluated in a
    // click handler, before any await. WebKit only unlocks a context
    // when resume() is called inside that synchronous window; call it
    // one tick later (after even a single `await`) and it stays
    // suspended forever with no error. Not awaited here on purpose - see
    // reportIfAudioSuspended, which checks back once a caller's own
    // async setup has finished.
    audioCtx.resume().catch((err) => {
      overtureDiagnostics.resumeError = String(err && err.message ? err.message : err);
      overtureDiagnostics.log(`resume() rejected: ${overtureDiagnostics.resumeError}`);
    });
  }
  return audioCtx;
}

/**
 * The currently relevant diagnostics + analyser + ctx for the Sound
 * help panel - whichever audio path the visitor most recently touched.
 * There is no single "the" audio context on this page (the overture,
 * the wired demo and the two-device endpoint can each exist
 * independently), so the panel always reflects the last one used rather
 * than trying to merge three into one report.
 */
let activeAudioSource = null; // { label, ctx, analyser, diagnostics }

function setActiveAudioSource(label, ctx, analyser, diagnostics) {
  activeAudioSource = { label, ctx, analyser, diagnostics };
  renderSoundHelp();
}

/**
 * Tells a visitor when audio did not actually start, rather than leaving
 * them looking at a demo that is visibly running but silent. Call once a
 * demo's own async setup has settled, so `ctx.state` reflects the real
 * outcome of the resume() call above rather than its still-pending
 * promise. Also covers WebKit's `interrupted` state - see wired.js's own
 * doc on https://bugs.webkit.org/show_bug.cgi?id=273511.
 *
 * This only catches the case `ctx.state` can actually see. A context
 * that is `running` and genuinely producing no sound - the ambient
 * session category respecting the iOS silent switch - reports nothing
 * here by design; see `checkAudibleOrWarn` below for the check that
 * covers that gap instead.
 */
function reportIfAudioSuspended(ctx) {
  if (ctx && (ctx.state === 'suspended' || ctx.state === 'interrupted')) {
    micDiagnostic.textContent = ctx.state === 'interrupted'
      ? 'Audio was interrupted (another app or a call likely took the audio session) - press the button again, or use Resume sound in Sound help below.'
      : 'Audio has not started for this tab yet - if this stays silent, check the device is not muted (the iOS silent switch mutes web audio too) and try the button again.';
    micDiagnostic.className = 'diagnostic diagnostic--warning';
    return true;
  }
  return false;
}

/**
 * The other half of the fix: a context can stay `running` throughout
 * and still never produce audible output on iOS (WebKit's ambient
 * session category respects the silent switch - see
 * audio-diagnostics.js). `ensurePlaybackAudioSession` is the real fix
 * for that; this is the honesty check on top of it, actually measuring
 * output via the analyser rather than trusting `ctx.state` alone, which
 * is exactly the case the old suspended-only warning always missed.
 */
async function checkAudibleOrWarn(ctx, analyser, diagnostics) {
  const heard = await waitForAudibleSignal(ctx, analyser);
  diagnostics.recordState(ctx);
  if (heard) {
    diagnostics.mark('rmsNonZero');
    renderSoundHelp();
    return true;
  }
  if (ctx && (ctx.state === 'suspended' || ctx.state === 'interrupted')) {
    // Already reported by reportIfAudioSuspended - nothing new to add.
    renderSoundHelp();
    return false;
  }
  micDiagnostic.textContent = 'Audio is running but no sound has been detected - check the mute switch and volume, then try Resume sound in Sound help below.';
  micDiagnostic.className = 'diagnostic diagnostic--warning';
  renderSoundHelp();
  return false;
}

// -----------------------------------------------------------------------
// Sound help - a visitor on an iPhone is the only person who can ever
// see whether this actually worked, and Dan is the only person who can
// test on one. This panel exists so the page can tell him what it knows
// rather than presenting a silent demo with nothing to go on.
// -----------------------------------------------------------------------
const CHECKPOINT_LABELS = {
  fetched: 'WASM fetched',
  moduleAdded: 'Worklet module loaded',
  wasmReady: 'WASM instantiated and ready',
  currentTimeAdvancing: 'Audio clock advancing',
  rmsNonZero: 'Output signal detected',
};

function renderSoundHelp() {
  soundHelpCheckpoints.innerHTML = '';
  if (!activeAudioSource) {
    const li = document.createElement('li');
    li.textContent = 'Nothing has tried to play audio yet - press Dial, Play the whole overture, or Enable microphone.';
    soundHelpCheckpoints.appendChild(li);
    soundHelpState.textContent = '';
    return;
  }
  const { label, ctx, analyser, diagnostics } = activeAudioSource;
  diagnostics.recordState(ctx);
  if (ctx && ctx.state === 'running' && analyser) {
    diagnostics.checkpoints.currentTimeAdvancing = ctx.currentTime > 0;
  }

  for (const [key, text] of Object.entries(CHECKPOINT_LABELS)) {
    const li = document.createElement('li');
    const done = diagnostics.checkpoints[key];
    li.textContent = `${done ? '[x]' : '[ ]'} ${text}`;
    soundHelpCheckpoints.appendChild(li);
  }

  const rms = analyser ? computeRms(analyser) : null;
  const stateLine = `${label}: context ${ctx ? ctx.state : 'not created'}${rms !== null ? `, output RMS ${rms.toFixed(4)}` : ''}${diagnostics.resumeError ? `, last resume() error: ${diagnostics.resumeError}` : ''}`;
  soundHelpState.textContent = stateLine;
}

resumeSoundBtn.addEventListener('click', () => {
  // A real click, unlike visibilitychange (see wired.js/modem.js's own
  // doc on why that alone is not a guaranteed user-activation signal for
  // WebKit's resume rules). Resumes everything that currently exists,
  // regardless of the state each thinks it is in - harmless to call
  // resume() on a context that is already running, and this button
  // exists specifically for the case where the automatic path did not
  // work and only a real gesture will.
  ensurePlaybackAudioSession();
  if (audioCtx) {
    audioCtx.resume().catch((err) => {
      overtureDiagnostics.resumeError = String(err && err.message ? err.message : err);
    });
  }
  if (wired && wired.ctx) {
    wired.ctx.resume().catch((err) => {
      wired.diagnostics.resumeError = String(err && err.message ? err.message : err);
    });
  }
  if (endpoint && endpoint.ctx) {
    endpoint.ctx.resume().catch((err) => {
      endpoint.diagnostics.resumeError = String(err && err.message ? err.message : err);
    });
  }
  renderSoundHelp();
});

copyDiagnosticsBtn.addEventListener('click', async () => {
  const lines = [
    `modem.dbhq.uk diagnostics`,
    `captured: ${new Date().toISOString()}`,
    `page last-modified: ${document.lastModified}`,
    `user agent: ${navigator.userAgent}`,
    `secure context: ${window.isSecureContext}`,
    `audioSession: ${'audioSession' in navigator ? (navigator.audioSession.type || '(no type set)') : 'not exposed by this browser'}`,
  ];
  if (activeAudioSource) {
    const { label, ctx, analyser, diagnostics } = activeAudioSource;
    diagnostics.recordState(ctx);
    lines.push('', `active source: ${label}`, `context state: ${ctx ? ctx.state : 'none'}`, `currentTime: ${ctx ? ctx.currentTime.toFixed(3) : 'n/a'}`);
    if (analyser) lines.push(`output RMS: ${computeRms(analyser).toFixed(5)}`);
    lines.push(`checkpoints: ${JSON.stringify(diagnostics.checkpoints)}`);
    lines.push(`state history: ${diagnostics.stateHistory.map((s) => `${s.t}ms:${s.state}`).join(' -> ')}`);
    if (diagnostics.resumeError) lines.push(`last resume() error: ${diagnostics.resumeError}`);
    lines.push('events:', ...diagnostics.events.map((e) => `  ${e.t}ms  ${e.text}`));
  } else {
    lines.push('', 'no audio path has been used yet this session');
  }
  lines.push('', `CSP violations: ${cspViolations.length}`);
  for (const v of cspViolations) {
    lines.push(`  ${v.directive} blocked ${v.blockedURI} (${v.sourceFile}:${v.lineNumber})`);
  }

  const report = lines.join('\n');
  try {
    await navigator.clipboard.writeText(report);
    copyDiagnosticsStatus.textContent = 'Copied to clipboard.';
  } catch (err) {
    console.error('clipboard write failed', err);
    copyDiagnosticsStatus.textContent = 'Could not copy automatically - select and copy the text below.';
    const existing = copyDiagnosticsStatus.parentElement.querySelector('.sound-help__report');
    if (existing) existing.remove();
    const pre = document.createElement('pre');
    pre.className = 'sound-help__report';
    pre.textContent = report;
    copyDiagnosticsStatus.after(pre);
  }
});

// iOS suspends every AudioContext when the page is backgrounded, and
// does not resume it automatically when the visitor comes back - left
// alone, that is a demo that looks like it is still running but has
// gone silent. Re-resume whatever is currently live the moment the page
// is visible again, from inside the same visibilitychange handler that
// fires the moment a person switches back to the tab (itself a strong
// enough activation signal for WebKit's own resume rules, though not
// guaranteed - see the Resume sound button above for the explicit
// fallback). Also covers `interrupted`, not only `suspended`.
document.addEventListener('visibilitychange', () => {
  if (document.visibilityState !== 'visible') return;
  if (audioCtx && (audioCtx.state === 'suspended' || audioCtx.state === 'interrupted')) {
    audioCtx.resume().catch((err) => {
      overtureDiagnostics.resumeError = String(err && err.message ? err.message : err);
    });
  }
  if (wired) wired.resumeIfSuspended();
  if (endpoint) endpoint.resumeIfSuspended();
  renderSoundHelp();
});

async function prerenderOverture(ctx) {
  const sampleRate = 8000; // modem-core's own internal rate - no resampling
  const response = await fetch('modem.wasm');
  const bytes = await response.arrayBuffer();
  const exportsHandle = await instantiateModemModule(bytes);
  const session = new SessionHandle(exportsHandle, { sampleRate, role: Role.ORIGINATE, duplex: Duplex.HALF_PING_PONG });
  // SessionHandle.dial wants raw bytes, not a string - ModemEndpoint.dial
  // (modem.js) does this same encode() call for its callers; this is the
  // same low-level SessionHandle those callers sit on top of.
  session.dial(new TextEncoder().encode('01234567890'));

  const BLOCK = 256;
  const CONNECTED_TAIL_S = 1.2; // enough to hear CONNECT 300 land, no longer
  const SAFETY_CAP_S = 20; // the overture's own documented upper bound

  const chunks = [];
  const segments = [];
  let cursor = 0;
  let current = null;
  let connectedAt = null;
  const buf = new Float32Array(BLOCK);

  for (;;) {
    session.processOut(buf);
    chunks.push(buf.slice());
    const state = session.state();
    const stage = session.stage();
    const label = state === SessionState.CONNECTED ? 'connected' : stage;

    if (current === null || current.label !== label) {
      if (current) current.endSample = cursor;
      current = { label, startSample: cursor, endSample: null };
      segments.push(current);
    }
    cursor += BLOCK;

    if (state === SessionState.CONNECTED) {
      if (connectedAt === null) connectedAt = cursor;
      if ((cursor - connectedAt) / sampleRate >= CONNECTED_TAIL_S) break;
    }
    if (cursor / sampleRate > SAFETY_CAP_S) break;
  }
  current.endSample = cursor;
  session.free();

  const master = new Float32Array(cursor);
  let offset = 0;
  for (const chunk of chunks) {
    master.set(chunk, offset);
    offset += chunk.length;
  }

  const audioBuffer = ctx.createBuffer(1, master.length, sampleRate);
  audioBuffer.copyToChannel(master, 0);

  const stageSegments = new Map();
  for (const seg of segments) {
    if (typeof seg.label === 'number') stageSegments.set(seg.label, seg);
  }

  return { audioBuffer, segments, stageSegments, sampleRate };
}

function ensurePrerendered() {
  const ctx = ensureAudioContext();
  if (!prerenderPromise) {
    prerenderPromise = prerenderOverture(ctx);
  }
  return prerenderPromise;
}

let activeTimers = [];
function clearScheduledAnnotations() {
  for (const t of activeTimers) clearTimeout(t);
  activeTimers = [];
}

function labelText(label) {
  return label === 'connected' ? 'CONNECT 300' : STAGE_NAMES[label];
}

function setActivePhaseRow(label) {
  const rows = phaseListEl.querySelectorAll('.phase-row');
  rows.forEach((row) => row.classList.remove('phase-row--active'));
  if (typeof label === 'number') {
    const row = phaseListEl.querySelector(`[data-stage="${label}"]`);
    if (row) row.classList.add('phase-row--active');
  }
}

// -----------------------------------------------------------------------
// Exactly one clip plays at a time - the Dial button's full overture and
// every phase-row's own slice all go through `playSlice`, and starting
// any one of them stops whatever else was running first. Before this,
// each phase button only disabled itself, so two phases (or a phase and
// the full overture) could play over each other, both painting the one
// waterfall and both talking over the same speakers.
// -----------------------------------------------------------------------
let currentPlayback = null;

function stopCurrentPlayback() {
  if (currentPlayback) {
    const playing = currentPlayback;
    currentPlayback = null;
    playing.stop();
  }
}

/** Plays `[startSample, endSample)` of the prerendered buffer through the
 * waterfall's analyser, resolving once playback ends (naturally, or via
 * `stopCurrentPlayback`). Pre-empts whatever else was already playing. */
function playSlice({ audioBuffer, sampleRate }, startSample, endSample) {
  stopCurrentPlayback();

  const ctx = ensureAudioContext();
  const analyser = ctx.createAnalyser();
  analyser.fftSize = 2048;
  const source = ctx.createBufferSource();
  source.buffer = audioBuffer;
  source.connect(analyser);
  analyser.connect(ctx.destination);

  let raf = null;
  const draw = () => {
    waterfall.frame(analyser, ctx.sampleRate);
    raf = requestAnimationFrame(draw);
  };
  raf = requestAnimationFrame(draw);

  const offset = startSample / sampleRate;
  const duration = (endSample - startSample) / sampleRate;
  source.start(0, offset, duration);

  const token = {
    stop() {
      try {
        source.stop();
      } catch (_err) {
        // Already stopped or never started - nothing left to do.
      }
    },
  };
  currentPlayback = token;

  return new Promise((resolve) => {
    source.onended = () => {
      cancelAnimationFrame(raf);
      if (currentPlayback === token) currentPlayback = null;
      resolve();
    };
  });
}

async function playFullOverture() {
  overtureBtn.disabled = true;
  resetAllPhaseButtons();
  nowPlaying.textContent = 'Loading...';
  terminalOutput.innerHTML = '';
  waterfall.reset();

  const rendered = await ensurePrerendered();
  reportIfAudioSuspended(audioCtx);
  setActiveAudioSource('overture', audioCtx, null, overtureDiagnostics);
  appendTerminalLine(terminalOutput, 'ATDT01234567890', { command: true });

  clearScheduledAnnotations();
  for (const seg of rendered.segments) {
    const atMs = (seg.startSample / rendered.sampleRate) * 1000;
    activeTimers.push(setTimeout(() => {
      nowPlaying.textContent = labelText(seg.label);
      setActivePhaseRow(seg.label);
      if (seg.label === 'connected') {
        appendTerminalLine(terminalOutput, 'CONNECT 300', { command: true });
      } else {
        appendTerminalLine(terminalOutput, STAGE_NAMES[seg.label]);
      }
    }, atMs));
  }

  await playSlice(rendered, 0, rendered.segments[rendered.segments.length - 1].endSample);

  clearScheduledAnnotations();
  nowPlaying.textContent = 'Idle';
  setActivePhaseRow(null);
  overtureBtn.disabled = false;
}

overtureBtn.addEventListener('click', () => {
  playFullOverture().catch((err) => {
    console.error(err);
    nowPlaying.textContent = 'Playback failed - press play to try again';
    overtureBtn.disabled = false;
  });
});

// -----------------------------------------------------------------------
// The explainer: one phase-row per stage, each playing its own slice of
// the identical rendering the dial button uses. Exactly one plays at a
// time (see `currentPlayback` above) - clicking a row's button while it
// is the one playing stops it early; clicking a different row's button
// switches to that clip instead of layering on top of the first.
// -----------------------------------------------------------------------
let activePhaseIndex = null;

function resetAllPhaseButtons() {
  phaseListEl.querySelectorAll('.phase-row__play').forEach((b) => {
    b.textContent = 'Play';
  });
  activePhaseIndex = null;
}

PHASES.forEach((phase, index) => {
  const li = document.createElement('li');
  li.className = 'phase-row';
  li.dataset.stage = String(index);

  const button = document.createElement('button');
  button.type = 'button';
  button.className = 'phase-row__play';
  button.textContent = 'Play';
  button.addEventListener('click', async () => {
    if (activePhaseIndex === index) {
      // Already the one playing - a second click stops it, and does not
      // start anything new.
      stopCurrentPlayback();
      return;
    }

    resetAllPhaseButtons();
    activePhaseIndex = index;
    button.textContent = 'Stop';
    try {
      const rendered = await ensurePrerendered();
      const seg = rendered.stageSegments.get(index);
      if (!seg) throw new Error(`stage ${index} did not appear in the rendered overture`);
      nowPlaying.textContent = STAGE_NAMES[index];
      setActivePhaseRow(index);
      await playSlice(rendered, seg.startSample, seg.endSample);
    } catch (err) {
      console.error(err);
    } finally {
      // Guards against a preempted clip's own cleanup running after a
      // newer one has already taken over - see playSlice's token
      // handling, which is the other half of this same guard.
      if (activePhaseIndex === index) {
        nowPlaying.textContent = 'Idle';
        setActivePhaseRow(null);
        button.textContent = 'Play';
        activePhaseIndex = null;
      }
    }
  });

  // One header line (the control beside its own phase name), the
  // description flowing full width beneath it - not the button run
  // down the row's full height beside a text column it narrows.
  const header = document.createElement('div');
  header.className = 'phase-row__header';
  const h3 = document.createElement('h3');
  h3.className = 'phase-row__label';
  h3.textContent = phase.label;
  header.appendChild(button);
  header.appendChild(h3);

  const p = document.createElement('p');
  p.className = 'phase-row__description';
  p.textContent = phase.description;

  li.appendChild(header);
  li.appendChild(p);
  phaseListEl.appendChild(li);
});

// -----------------------------------------------------------------------
// Routing: three routes behind one application - /demo, /originate,
// /receive - plus the plain landing (three buttons) at the root path,
// and #demo kept working as a legacy alias for /demo. Routes carry the
// role; nothing about the call itself (digits, connection phase) ever
// lives in the URL.
//
// The rule that shapes everything below: an internal tap on one of the
// three landing buttons starts that route immediately - clicking the
// button is itself the explicit gesture, so there is nothing left to
// confirm - while a direct link or a reload landing straight on a route
// must never play audio or ask for a microphone on its own. Both cases
// run through the exact same `startRoute`; what differs is only whether
// something else already supplied the gesture (a real click, handled
// synchronously inside the launcher buttons' own listeners) or whether
// this page has to ask for one first (`route-start-block`, populated by
// `showRouteStart` and only ever wired to call `startRoute` from inside
// its own click handler).
// -----------------------------------------------------------------------
function routeForLocation() {
  let path = location.pathname.replace(/\/index\.html$/, '');
  if (path.length > 1) path = path.replace(/\/+$/, '');
  if (path.endsWith('/demo')) return 'demo';
  if (path.endsWith('/originate')) return 'originate';
  if (path.endsWith('/receive')) return 'receive';
  // Legacy alias: a shared link to the old #demo hash on the plain root
  // path still has to work.
  if (location.hash === '#demo') return 'demo';
  return null;
}

const ROUTE_START_COPY = {
  demo: 'A direct link never plays audio on its own - press Start to hear both ends connect right here.',
  originate: 'This device will dial out - it needs your microphone, asked for only once you press Start.',
  receive: 'This device will listen for a call - it needs your microphone, asked for only once you press Start.',
};
const ROUTE_START_LABEL = {
  demo: 'Start demo',
  originate: 'Start originating modem',
  receive: 'Start receiving modem',
};

let pendingRoute = null;

function showLanding() {
  pendingRoute = null;
  launcher.hidden = false;
  routeStartBlock.hidden = true;
  wiredPanel.hidden = true;
  endpointPanel.hidden = true;
}

function showRouteStart(route) {
  pendingRoute = route;
  launcher.hidden = true;
  routeStartBlock.hidden = false;
  routeStartCopy.textContent = ROUTE_START_COPY[route];
  routeStartBtn.textContent = ROUTE_START_LABEL[route];
  wiredPanel.hidden = true;
  endpointPanel.hidden = true;
}

function initRouting() {
  const route = routeForLocation();
  if (route) {
    showRouteStart(route);
  } else {
    showLanding();
  }
}

async function startRoute(route) {
  if (route === 'demo') await startDemo();
  else if (route === 'originate') await startEndpointRoute(Role.ORIGINATE);
  else if (route === 'receive') await startEndpointRoute(Role.ANSWER);
}

launchDemoBtn.addEventListener('click', () => {
  history.pushState(null, '', '/demo');
  launcher.hidden = true;
  startRoute('demo');
});
launchOriginateBtn.addEventListener('click', () => {
  history.pushState(null, '', '/originate');
  launcher.hidden = true;
  startRoute('originate');
});
launchReceiveBtn.addEventListener('click', () => {
  history.pushState(null, '', '/receive');
  launcher.hidden = true;
  startRoute('receive');
});

routeStartBtn.addEventListener('click', () => {
  if (!pendingRoute) return;
  const route = pendingRoute;
  routeStartBlock.hidden = true;
  startRoute(route);
});

/** Back (either panel's own button) and Escape both fully exit to the
 * landing - there is no intermediate "in-page but not full-viewport"
 * state any more now that all three routes are dedicated full-viewport
 * views, so there is nothing to shrink back into. */
async function exitToLanding() {
  exitAppMode();
  if (wired) await teardownWired();
  if (endpoint) await teardownEndpoint();
  showLanding();
  if (location.pathname !== '/' || location.hash) {
    history.pushState(null, '', '/');
  }
}

appModeBackBtn.addEventListener('click', exitToLanding);
endpointBackBtn.addEventListener('click', exitToLanding);

document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape' && document.body.classList.contains('app-mode')) exitToLanding();
});

// Back/forward navigation must not auto-start anything either - the same
// rule a fresh load follows. Tear down whatever was live and re-evaluate
// the new location exactly as a fresh load would.
window.addEventListener('popstate', async () => {
  exitAppMode();
  if (wired) await teardownWired();
  if (endpoint) await teardownEndpoint();
  initRouting();
});

// -----------------------------------------------------------------------
// app-mode - the full-viewport view every one of the three routes gets
// while live (Dan, 8 Sep 2026: "make the demo fill the phone screen on
// mobile nicely, almost become an app" - now every viewport size, and
// /originate and /receive's own view too, not the wired demo only). See
// style.css's own doc on why the shell rules target `.endpoint.app-mode`
// rather than `.wired.app-mode` specifically.
// -----------------------------------------------------------------------
let liveAppModePanel = null;

function enterAppModeFor(panel) {
  liveAppModePanel = panel;
  document.body.classList.add('app-mode');
  panel.classList.add('app-mode');
  updateAppModeViewportHeight();
  const backBtn = panel.querySelector('.app-mode-back');
  if (backBtn) backBtn.focus();
}

function exitAppMode() {
  if (liveAppModePanel) {
    liveAppModePanel.classList.remove('app-mode');
    liveAppModePanel.style.removeProperty('height');
  }
  document.body.classList.remove('app-mode');
  liveAppModePanel = null;
}

/**
 * `100dvh` already tracks the browser's own address bar; it does not
 * reliably track the on-screen keyboard on every WebKit version. While
 * app mode is active, the visualViewport API (where present) is the
 * more honest source for "how much space is actually left above the
 * keyboard" - setting the panel's own height directly to it keeps the
 * composer visible above the keyboard rather than covered by it,
 * instead of a fixed-height box the keyboard simply overlaps.
 */
function updateAppModeViewportHeight() {
  if (!liveAppModePanel) return;
  if (window.visualViewport) {
    liveAppModePanel.style.height = `${window.visualViewport.height}px`;
  }
}

if (window.visualViewport) {
  window.visualViewport.addEventListener('resize', updateAppModeViewportHeight);
}

// -----------------------------------------------------------------------
// The automatic bidirectional data check - the actual success criterion
// for a real call in either mode (carrier detection alone is not
// success). A fixed, non-secret marker rather than anything a visitor
// could type - it is filtered out of both transcripts on arrival (see
// the 'data' listeners below), never shown as though it were real chat,
// and never printed as fabricated modem output either: it only ever
// drives this diagnostic line, outside the transcript.
// -----------------------------------------------------------------------
const CANARY = 'MODEM-CHECK-OK';
const DATA_CHECK_TIMEOUT_MS = 10000;

/**
 * Demo's own check: both real Sessions live in this one page, so the
 * joint verdict can be computed and shown directly. Originate already
 * holds the turn the instant both ends connect, so it sends first;
 * answer only ever sends its own canary back once its own `status` event
 * genuinely reports `hasTurn`, never on a fixed timer.
 *
 * `yieldTurn` is called a real ~800ms after `send`, not back to back.
 * The queueing order alone (`process_out`'s "yielding" bypass keeps
 * draining `tx` in order regardless of exactly when `hasTurn` itself
 * flips - see modem-core/src/session.rs's own doc) looked sufficient on
 * paper, but measured directly it was not: calling `yieldTurn`
 * immediately after `send` left the far end's `hasTurn` never once
 * observed true for the rest of the check window, even though the data
 * itself had already decoded correctly moments before - a real,
 * reproducible timing sensitivity around queueing a Turn packet with no
 * gap after other data, not a one-off flake. `modem-core`'s own test
 * suite never actually exercises this shape either: every hand-over test
 * there settles between operations (see `session.rs`'s own `settle`
 * helper), never queues a Turn packet immediately behind data with
 * nothing between them. A real settle here matches that established
 * convention rather than fighting it.
 */
function startWiredDataCheck() {
  let aReceivedB = false;
  let bReceivedA = false;
  let bSent = false;
  wiredDataCheck.textContent = 'Checking both directions carry real data...';
  wiredDataCheck.className = 'diagnostic';

  const onData = (e) => {
    const { side, bytes } = e.detail;
    const text = decodeWired(bytes);
    if (side === 'b' && text.includes(CANARY)) bReceivedA = true;
    if (side === 'a' && text.includes(CANARY)) aReceivedB = true;
    maybeFinish();
  };
  const onStatus = (e) => {
    const { b } = e.detail;
    if (!bSent && b.hasTurn && b.state === SessionState.CONNECTED) {
      bSent = true;
      wired.send('b', CANARY);
      // A real gap before yielding, not back-to-back - matching
      // modem-core's own test convention (every hand-over test settles
      // between operations, never queues a Turn packet immediately
      // behind data with no gap). Measured directly: yielding
      // immediately after send() here left the far end's `hasTurn`
      // never once observed true for the rest of the check window, even
      // though the data itself had already decoded correctly - a real,
      // reproducible timing sensitivity, not a one-off flake.
      setTimeout(() => wired.yieldTurn('b'), 800);
    }
  };

  function cleanup() {
    wired.removeEventListener('data', onData);
    wired.removeEventListener('status', onStatus);
    clearTimeout(timer);
  }
  function maybeFinish() {
    if (aReceivedB && bReceivedA) {
      wiredDataCheck.textContent = 'Bidirectional data check: passed - both ends received real bytes from the other.';
      wiredDataCheck.className = 'diagnostic';
      cleanup();
    }
  }
  const timer = setTimeout(() => {
    if (!(aReceivedB && bReceivedA)) {
      const missing = [];
      if (!bReceivedA) missing.push('originate to answer');
      if (!aReceivedB) missing.push('answer to originate');
      wiredDataCheck.textContent = `Bidirectional data check: failed - ${missing.join(' and ')} did not arrive within 10s.`;
      wiredDataCheck.className = 'diagnostic diagnostic--warning';
    }
    cleanup();
  }, DATA_CHECK_TIMEOUT_MS);

  wired.addEventListener('data', onData);
  wired.addEventListener('status', onStatus);
  wired.send('a', CANARY);
  setTimeout(() => wired.yieldTurn('a'), 800);
}

/**
 * The two-device check: this page only ever has one real Session, so it
 * can only honestly claim what it can measure - whether *this* end
 * received the far end's canary. That is still the real, load-bearing
 * proof for this end's own screen: with both pages open (the two-device
 * routes' own standing instruction), a visitor sees "received" appear on
 * both physical devices, together, which is what genuinely bidirectional
 * data looks like across two independent endpoints - never inferred from
 * one side alone. Same turn logic as the wired check, and it works
 * unmodified on both /originate and /receive: originate already holds
 * the turn at Connected and sends immediately; answer's own `status`
 * event only reports `hasTurn` once the real acoustic Turn packet has
 * actually arrived, and sends only then.
 */
function startEndpointDataCheck() {
  let received = false;
  let sentOwn = false;
  endpointDataCheck.textContent = 'Checking this end can send and receive real data...';
  endpointDataCheck.className = 'diagnostic';

  const onStatus = (e) => {
    if (!sentOwn && e.detail.hasTurn && e.detail.state === SessionState.CONNECTED) {
      sentOwn = true;
      endpoint.send(CANARY);
      // A real gap, not back-to-back - see startWiredDataCheck's own
      // doc for the measured reason this matters.
      setTimeout(() => endpoint.yieldTurn(), 800);
    }
  };
  const onData = (e) => {
    const text = new TextDecoder().decode(e.detail);
    if (text.includes(CANARY)) {
      received = true;
      endpointDataCheck.textContent = 'Bidirectional data check: this end received real bytes from the far end.';
      endpointDataCheck.className = 'diagnostic';
      cleanup();
    }
  };

  function cleanup() {
    endpoint.removeEventListener('status', onStatus);
    endpoint.removeEventListener('data', onData);
    clearTimeout(timer);
  }
  const timer = setTimeout(() => {
    if (!received) {
      endpointDataCheck.textContent = 'Bidirectional data check: nothing arrived from the far end within 10s - the acoustic link connected but data did not get through. A convincing-looking call is not the same as one that actually works.';
      endpointDataCheck.className = 'diagnostic diagnostic--warning';
    }
    cleanup();
  }, DATA_CHECK_TIMEOUT_MS);

  endpoint.addEventListener('status', onStatus);
  endpoint.addEventListener('data', onData);
}

// -----------------------------------------------------------------------
// /demo - two real Sessions cross-wired in software, right here in the
// page, the browser mirror of modem-audio/src/transport.rs's
// WiredTransport. No microphone and no permission prompt: both ends live
// in this page and the mixed signal plays through the visitor's own
// speakers.
//
// Answer auto-answers, matching the binary: `modem --single --acoustic
// --answer` answers at startup with nothing typed into it. There is no
// separate "ATA (answer)" control - `wired.answer()` runs as soon as the
// session pair exists.
// -----------------------------------------------------------------------
let wired = null;
let lastWiredA = null;
let lastWiredB = null;

function endpointStateName(state) {
  switch (state) {
    case SessionState.IDLE: return 'IDLE';
    case SessionState.DIALLING: return 'DIALLING';
    case SessionState.ANSWERING: return 'ANSWERING';
    case SessionState.CONNECTED: return 'CONNECTED';
    default: return String(state);
  }
}

/** One word for a panel's own status line - the long combined string
 * (state/stage/turn/carrier) now lives only in the shared phase line
 * below, so the two are not saying almost the same thing twice. */
function wiredShortStatus(status) {
  return endpointStateName(status.state);
}

/** The call's overall phase, shared above both panels rather than
 * repeated inside each - "both ends live" is one story, not two. */
function wiredPhaseLine(a, b) {
  if (a.state === SessionState.CONNECTED && b.state === SessionState.CONNECTED) {
    return 'CONNECTED';
  }
  if (a.state === SessionState.IDLE) {
    return 'IDLE - press ATDT to dial';
  }
  const stage = typeof a.stage === 'number' && a.stage >= 0 ? a.stage
    : typeof b.stage === 'number' && b.stage >= 0 ? b.stage
    : null;
  const stageName = stage !== null ? STAGE_NAMES[stage] : 'connecting';
  return `Handshake: ${stageName}`;
}

/**
 * Each panel's own honest gloss on the call's real phase - outside the
 * modem transcript on purpose (never the same element real modem output
 * lands in - see the top-level doc on never inventing modem output).
 * Sourced from the real overture/session state both ends already carry
 * in their own `status` payload: legitimate "shared call events" for
 * Demo specifically, because both ends are genuinely real and already in
 * this one page (not a stand-in for the acoustic observation the
 * two-device routes need instead - see their own captions below).
 * Originate's own caption never claims the far end is ringing, only ever
 * its own actual stage; answer's is driven by originate's real
 * stage/ring number precisely because nothing here is a timer guessing
 * at elapsed time.
 */
function wiredCaptionFor(side, a, b) {
  if (side === 'a') {
    if (a.state === SessionState.CONNECTED) return 'Connected';
    if (typeof a.stage === 'number' && a.stage === 3) return 'Calling - ringback (answers after 2 rings)';
    if (typeof a.stage === 'number' && a.stage >= 0) return 'Calling';
    return '';
  }
  if (b.state === SessionState.CONNECTED) return 'Connected';
  if (typeof a.stage !== 'number' || a.stage < 0) return 'Listening';
  if (a.stage < 3) return 'Listening';
  if (a.stage === 3) {
    return a.ringNumber ? `Incoming call - ring ${a.ringNumber} of 2` : 'Incoming call';
  }
  return 'Auto-answering';
}

function updateWiredComposerEnablement() {
  const bothConnected = !!lastWiredA && !!lastWiredB
    && lastWiredA.state === SessionState.CONNECTED
    && lastWiredB.state === SessionState.CONNECTED;
  wiredChat.disabled = !bothConnected;
  wiredSendBtn.disabled = !bothConnected;
}

/** Dials from originate with whatever is in the digits field - shared by
 * the automatic first dial (below) and the panel's own "ATDT (dial)"
 * redial button, so the two never drift into logging the command
 * differently. */
function dialWired() {
  const digits = wiredDigits.value || '0';
  wired.dial(digits);
  appendTerminalLine(wiredLogA, `ATDT${digits}`, { command: true });
}

let dialStarting = false;
let wiredDataCheckStarted = false;

async function startDemo() {
  if (dialStarting || wired) return;
  dialStarting = true;
  try {
    wired = new WiredEndpoint();
    await wired.init({ duplex: Duplex.HALF_PING_PONG });
    reportIfAudioSuspended(wired.ctx);
    setActiveAudioSource('demo', wired.ctx, wired.analyser, wired.diagnostics);
    wiredDataCheckStarted = false;

    wired.addEventListener('status', (e) => {
      const { a, b } = e.detail;
      lastWiredA = a;
      lastWiredB = b;
      wiredStatusA.textContent = wiredShortStatus(a);
      wiredStatusB.textContent = wiredShortStatus(b);
      wiredPhase.textContent = wiredPhaseLine(a, b);
      wiredCaptionA.textContent = wiredCaptionFor('a', a, b);
      wiredCaptionB.textContent = wiredCaptionFor('b', a, b);
      updateWiredComposerEnablement();
      wiredHangupBtn.disabled = a.state === SessionState.IDLE && b.state === SessionState.IDLE;
      if (!wiredDataCheckStarted && a.state === SessionState.CONNECTED && b.state === SessionState.CONNECTED) {
        wiredDataCheckStarted = true;
        startWiredDataCheck();
      }
      if (a.state === SessionState.IDLE && b.state === SessionState.IDLE) {
        wiredDataCheckStarted = false;
      }
    });

    wired.addEventListener('data', (e) => {
      const { side, bytes } = e.detail;
      const text = decodeWired(bytes);
      if (text.includes(CANARY)) return;
      appendTerminalLine(side === 'a' ? wiredLogA : wiredLogB, text);
    });

    wired.addEventListener('error', (e) => {
      appendTerminalLine(wiredLogA, `error: ${e.detail}`);
    });

    // Auto-answer - see this section's own doc above.
    wired.answer();

    startWiredWaterfall(wired);
    enterAppModeFor(wiredPanel);
    wiredPanel.hidden = false;
    // Auto-dial too - pressing Demo once is the entire demo, not the
    // first of several steps.
    dialWired();
    // Not awaited - a background honesty check (see checkAudibleOrWarn's
    // own doc), not something the dial flow itself should wait on.
    checkAudibleOrWarn(wired.ctx, wired.analyser, wired.diagnostics);
  } catch (err) {
    console.error(err);
    micDiagnostic.textContent = `Could not start the demo: ${err.message || err}`;
    micDiagnostic.className = 'diagnostic diagnostic--warning';
    await exitToLanding();
  } finally {
    dialStarting = false;
  }
}

/** Fully releases the audio graph rather than relying on hangup() alone -
 * see wired.js's own stop() doc: an idle Session outputs silence, but
 * the node itself keeps rendering it until the context closes. */
async function teardownWired() {
  if (!wired) return;
  await wired.stop();
  wired = null;
  lastWiredA = null;
  lastWiredB = null;
  stopWiredWaterfall();
  wiredPanel.hidden = true;
  wiredLogA.innerHTML = '';
  wiredLogB.innerHTML = '';
  wiredStatusA.textContent = 'IDLE';
  wiredStatusB.textContent = 'IDLE';
  wiredCaptionA.textContent = '';
  wiredCaptionB.textContent = '';
  wiredPhase.textContent = 'IDLE - press ATDT to dial';
  wiredDataCheck.textContent = '';
  updateWiredComposerEnablement();
  if (activeAudioSource && activeAudioSource.label === 'demo') {
    activeAudioSource = null;
    renderSoundHelp();
  }
}

wiredDialBtn.addEventListener('click', () => {
  if (wired) dialWired();
});

wiredHangupBtn.addEventListener('click', () => {
  if (wired) wired.hangup();
});

wiredStopBtn.addEventListener('click', teardownWired);

wiredSendBtn.addEventListener('click', () => {
  if (!wired || !wiredChat.value) return;
  const side = wiredSendSide.value === 'b' ? 'b' : 'a';
  wired.send(side, wiredChat.value);
  // Hands the turn back once this end is done - a chat composer that
  // never yielded left the far end with no way to ever reply (see
  // startWiredDataCheck's own doc on why this export exists at all). A
  // real gap before yielding, not back-to-back - see that same doc for
  // the measured reason a Turn packet queued with no gap after other
  // data left the far end's `hasTurn` never observed true.
  setTimeout(() => wired.yieldTurn(side), 800);
  appendTerminalLine(side === 'a' ? wiredLogA : wiredLogB, `> ${wiredChat.value}`);
  wiredChat.value = '';
});

wiredChat.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') wiredSendBtn.click();
});

// -----------------------------------------------------------------------
// /originate and /receive - one real endpoint, a raw microphone, role
// fixed by the route rather than chosen on the page. Both share this one
// implementation, parameterised only by `role`: the turn-based
// bidirectional check above already works unmodified on either end (see
// its own doc), and everything else that differs between the two - the
// heading, the intro copy, the QR/share block, the caption wording - is
// looked up from `role` below rather than forked into two copies.
// -----------------------------------------------------------------------
const FIXED_DIGITS = '0000';
const ORIGINATE_NO_ANSWER_MS = 20000;
const RECEIVE_NOTHING_MS = 10000;
const RECEIVE_MOVE_CLOSER_MS = 30000;
/** Below this, an analyser reading is treated as room noise, not
 * microphone activity - not a calibrated voice-activity threshold, just
 * "is anything audible reaching this input at all". */
const MIC_ACTIVITY_RMS = 0.01;

let endpoint = null;
let endpointRole = null;
let endpointClockStop = null;
let lastEndpointState = null;
let lastEndpointCarrier = false;
let micActivityRaf = null;

function startMicActivityIndicator() {
  stopMicActivityIndicator();
  const poll = () => {
    if (!endpoint || !endpoint.analyser) return;
    const rms = computeRms(endpoint.analyser);
    micActivityDot.classList.toggle('signal-indicator__dot--active', rms !== null && rms > MIC_ACTIVITY_RMS);
    micActivityRaf = requestAnimationFrame(poll);
  };
  micActivityRaf = requestAnimationFrame(poll);
}

function stopMicActivityIndicator() {
  if (micActivityRaf !== null) {
    cancelAnimationFrame(micActivityRaf);
    micActivityRaf = null;
  }
  micActivityDot.classList.remove('signal-indicator__dot--active');
}

/**
 * Runs `onTick(elapsedMs, running)` about twice a second for as long as
 * this route is live, accumulating elapsed time only while `ctx` reports
 * `running` - paused, not merely slowed, while suspended or interrupted,
 * so a deadline never counts down time the audio was not actually able
 * to use (Dan's brief: "Deadlines, counted only while audio is actually
 * running"). Returns a stop function.
 */
function startRunningClock(ctx, onTick) {
  let elapsedMs = 0;
  let last = performance.now();
  const id = setInterval(() => {
    const now = performance.now();
    const dt = now - last;
    last = now;
    const running = !!ctx && ctx.state === 'running';
    if (running) elapsedMs += dt;
    onTick(elapsedMs, running);
  }, 500);
  return () => clearInterval(id);
}

/** Never claims a detection that never happened - originate only ever
 * reports its own actual stage ("Calling", never "ringing" - it cannot
 * know that from its own ringback), answer only its own real state and
 * the real carrier flag. */
function endpointCaptionFor(role, state, stage, carrier) {
  if (role === Role.ORIGINATE) {
    if (state === SessionState.CONNECTED) return 'Connected';
    if (state === SessionState.DIALLING && typeof stage === 'number' && stage === 3) {
      return 'Calling - ringback (answers after 2 rings)';
    }
    if (state === SessionState.DIALLING && typeof stage === 'number' && stage >= 0) return 'Calling';
    return '';
  }
  if (state === SessionState.CONNECTED) return 'Connected';
  if (state === SessionState.ANSWERING) {
    return carrier ? 'Modem signal detected - connecting' : 'Listening for a call';
  }
  return '';
}

function updateEndpointDeadline(role, elapsedMs) {
  if (role === Role.ORIGINATE) {
    if (lastEndpointState === SessionState.DIALLING && elapsedMs > ORIGINATE_NO_ANSWER_MS) {
      endpointDeadline.textContent = 'No answer within 20s - ending this attempt.';
      endpointDeadline.className = 'diagnostic diagnostic--warning';
      if (endpoint) endpoint.hangup();
    }
    return;
  }
  if (lastEndpointState === SessionState.ANSWERING && !lastEndpointCarrier) {
    if (elapsedMs > RECEIVE_MOVE_CLOSER_MS) {
      endpointDeadline.textContent = 'Still nothing after 30s - try moving the devices closer (10-20cm), somewhere quieter, or use Demo instead.';
      endpointDeadline.className = 'diagnostic diagnostic--warning';
    } else if (elapsedMs > RECEIVE_NOTHING_MS) {
      endpointDeadline.textContent = 'Nothing recognised yet - make sure the originating device has started calling too.';
      endpointDeadline.className = 'diagnostic';
    }
  } else {
    endpointDeadline.textContent = '';
  }
}

function renderShareBlock(url) {
  qrCodeEl.innerHTML = '';
  if (window.qrcode) {
    try {
      const qr = window.qrcode(0, 'M');
      qr.addData(url);
      qr.make();
      qrCodeEl.innerHTML = qr.createSvgTag({ cellSize: 4, margin: 4, scalable: true });
    } catch (err) {
      console.error('QR generation failed', err);
    }
  }
  shareLinkInput.value = url;
  shareCopyStatus.textContent = '';
}

shareCopyBtn.addEventListener('click', async () => {
  try {
    await navigator.clipboard.writeText(shareLinkInput.value);
    shareCopyStatus.textContent = 'Copied to clipboard.';
  } catch (err) {
    console.error(err);
    shareLinkInput.select();
    shareCopyStatus.textContent = 'Could not copy automatically - select and copy the text above.';
  }
});

async function startEndpointRoute(role) {
  endpointRole = role;
  lastEndpointState = null;
  lastEndpointCarrier = false;
  endpointHeading.textContent = role === Role.ORIGINATE ? 'Originate - dialling out' : 'Receive - listening for a call';
  endpointIntro.textContent = role === Role.ORIGINATE
    ? 'This device dials out. There is no real telephone network behind this, so the digits are fixed and decorative - only the modem handshake and the connection underneath it are real.'
    : 'This device listens for a call and answers automatically - nothing to type.';
  wiredPanel.hidden = true;
  endpointPanel.hidden = false;
  enterAppModeFor(endpointPanel);
  endpointStatus.textContent = 'Waiting for microphone permission';
  endpointCaption.textContent = '';
  endpointCaption.className = 'endpoint__caption';
  endpointDeadline.textContent = '';
  endpointDataCheck.textContent = '';
  signalIndicators.hidden = true;
  chatLog.innerHTML = '';

  if (role === Role.ORIGINATE) {
    shareBlock.hidden = false;
    renderShareBlock(`${location.origin}/receive`);
  } else {
    shareBlock.hidden = true;
  }

  let dataCheckStarted = false;
  try {
    endpoint = new ModemEndpoint();
    await endpoint.init({ role, duplex: Duplex.HALF_PING_PONG });

    endpoint.addEventListener('status', (e) => {
      const { state, stage, carrier } = e.detail;
      lastEndpointState = state;
      lastEndpointCarrier = carrier;
      endpointStatus.textContent = endpointStateName(state);
      endpointCaption.textContent = endpointCaptionFor(role, state, stage, carrier);
      modemSignalDot.classList.toggle('signal-indicator__dot--active', carrier);
      const connected = state === SessionState.CONNECTED;
      chatInput.disabled = !connected;
      chatSendBtn.disabled = !connected;
      endpointHangupBtn.disabled = state === SessionState.IDLE;
      if (connected && !dataCheckStarted) {
        dataCheckStarted = true;
        startEndpointDataCheck();
      }
      if (state === SessionState.IDLE) {
        dataCheckStarted = false;
        endpointDataCheck.textContent = '';
      }
    });

    endpoint.addEventListener('data', (e) => {
      const text = new TextDecoder().decode(e.detail);
      if (text.includes(CANARY)) return;
      appendTerminalLine(chatLog, text);
    });

    endpoint.addEventListener('error', (e) => {
      appendTerminalLine(chatLog, `error: ${e.detail}`);
    });

    const diagnostics = await endpoint.openMicrophone();
    const summary = summariseMicDiagnostics(diagnostics);
    micDiagnostic.textContent = summary;
    micDiagnostic.className = diagnostics.warnings.length > 0 ? 'diagnostic diagnostic--warning' : 'diagnostic';
    reportIfAudioSuspended(endpoint.ctx);
    setActiveAudioSource('endpoint', endpoint.ctx, endpoint.analyser, endpoint.diagnostics);

    signalIndicators.hidden = false;
    startMicActivityIndicator();

    // Only from here - the microphone is actually capturing - does the
    // distance guidance belong on screen for /receive (Dan's brief: "once
    // actually capturing", not before).
    if (role === Role.ANSWER) {
      endpointIntro.textContent = 'Listening for a call. Put the two devices roughly 10-20cm apart, speakers and microphones uncovered, both pages open - a starting point to validate on real hardware, not a promise.';
    }

    endpointClockStop = startRunningClock(endpoint.ctx, (elapsedMs, running) => {
      if (!running) {
        endpointDeadline.textContent = 'Audio is suspended - tap to resume (see Sound help below).';
        endpointDeadline.className = 'diagnostic diagnostic--warning';
        return;
      }
      updateEndpointDeadline(role, elapsedMs);
    });

    if (role === Role.ORIGINATE) {
      endpoint.dial(FIXED_DIGITS);
      appendTerminalLine(chatLog, `ATDT${FIXED_DIGITS}`, { command: true });
    } else {
      endpoint.answer();
    }
    endpointHangupBtn.disabled = false;

    checkAudibleOrWarn(endpoint.ctx, endpoint.analyser, endpoint.diagnostics);
  } catch (err) {
    console.error(err);
    endpointStatus.textContent = 'IDLE';
    if (err && (err.name === 'NotAllowedError' || err.name === 'PermissionDeniedError')) {
      endpointCaption.textContent = 'Microphone permission was denied - allow access and press Start again.';
    } else {
      endpointCaption.textContent = `Could not start: ${err.message || err}`;
    }
    endpointCaption.className = 'endpoint__caption diagnostic--warning';
    await exitToLanding();
  }
}

/** The one control that fully releases the microphone rather than just
 * ending a call - spike/README.md finding 5's rule applies to more than
 * a forgotten carrier: a visitor should never have to close the tab to
 * know their microphone is off. */
async function teardownEndpoint() {
  stopMicActivityIndicator();
  if (endpointClockStop) {
    endpointClockStop();
    endpointClockStop = null;
  }
  if (endpoint) {
    await endpoint.stop();
  }
  endpoint = null;
  endpointRole = null;
  lastEndpointState = null;
  lastEndpointCarrier = false;
  endpointPanel.hidden = true;
  chatLog.innerHTML = '';
  endpointStatus.textContent = 'IDLE';
  endpointCaption.textContent = '';
  endpointDeadline.textContent = '';
  endpointDataCheck.textContent = '';
  signalIndicators.hidden = true;
  shareBlock.hidden = true;
  if (activeAudioSource && activeAudioSource.label === 'endpoint') {
    activeAudioSource = null;
    renderSoundHelp();
  }
}

endpointHangupBtn.addEventListener('click', () => {
  if (endpoint) endpoint.hangup();
});

endpointStopBtn.addEventListener('click', teardownEndpoint);

chatSendBtn.addEventListener('click', () => {
  if (!endpoint || !chatInput.value) return;
  endpoint.send(chatInput.value);
  // A real gap before yielding - see startWiredDataCheck's own doc for
  // the measured reason a Turn packet queued with no gap after other
  // data left the far end's `hasTurn` never observed true.
  setTimeout(() => endpoint.yieldTurn(), 800);
  appendTerminalLine(chatLog, `> ${chatInput.value}`);
  chatInput.value = '';
});

chatInput.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') chatSendBtn.click();
});

// A page navigating away must not leave a live microphone, a live wired
// call, or a carrier running - see spike/README.md finding 5 and both
// endpoints' own `stop()` docs. Best-effort: `beforeunload` cannot
// await, but stop() only tears down local objects (tracks, node,
// context), none of which need a network round trip.
window.addEventListener('beforeunload', () => {
  if (endpoint) endpoint.stop();
  if (wired) wired.stop();
});

// Populates the "nothing tried yet" state rather than leaving the panel
// empty until the first click - a visitor who opens Sound help before
// pressing anything should see that reflected accurately, not a blank list.
renderSoundHelp();

initRouting();
