// The page's own behaviour, extracted from an inline <script> so the
// Content-Security-Policy can stay strict. An inline block would need
// 'unsafe-inline' or a hash that changes every time the file does, and
// web/_gen/frames.py rewrites index.html, so a hash would go stale on
// its own. Blocking this script kills the whole demo, which is exactly
// what happened on the first deploy.
import { instantiateModemModule, SessionHandle, Role, Duplex, SessionState, STAGE_NAMES } from './session.js';
import { ModemEndpoint, summariseMicDiagnostics } from './modem.js';
import { WiredEndpoint, decode as decodeWired } from './wired.js';

// ---------------------------------------------------------------------
// The nine performed overture phases the explainer describes. Labels
// match STAGE_NAMES exactly, index for index, so the copy here can never
// silently drift from what the WASM session itself reports.
// ---------------------------------------------------------------------
const PHASES = [
  { label: STAGE_NAMES[0], description: 'The click of the line being seized - a relay closing, not a tone. It is the sound of the call existing at all, a beat before anything is dialled.' },
  { label: STAGE_NAMES[1], description: 'A continuous two-tone signal telling the exchange the line is ready to take a number. The UK pair is 350 and 450 Hz, different from the US pair most film and television dial tone actually is.' },
  { label: STAGE_NAMES[2], description: 'DTMF, the touch-tone digits. Each key sends two frequencies at once, one from a row and one from a column, so the exchange can tell exactly which one was pressed.' },
  { label: STAGE_NAMES[3], description: "The ringing tone you hear while the far end's phone rings, generated by your own exchange rather than the far end's phone. The UK cadence is a double ring: two short bursts of 400 and 450 Hz, then a pause." },
  { label: STAGE_NAMES[4], description: 'The calling indicator. Before anything else happens, the originating modem announces itself on a channel a voice call never touches, so the far end knows straight away that this is a data call.' },
  { label: STAGE_NAMES[5], description: 'The answer tone: 2100 Hz, its phase flipped 180 degrees every 450 milliseconds. Analogue phone networks ran echo suppressors that muted a call whenever it looked like only one side was talking, fine for speech and fatal for two modems talking at once. The phase reversals are a signal those suppressors were built to recognise, and switch themselves off for.' },
  { label: STAGE_NAMES[6], description: 'Call menu and joint menu. The two modems compare what modulations they each support and settle on the one they will actually use.' },
  { label: STAGE_NAMES[7], description: 'The acknowledgement that both ends agreed, followed by a short, deliberate silence: the last quiet moment before the two modems start probing the line itself.' },
  { label: STAGE_NAMES[8], description: "An impression of the real V.34-style probing that follows in an actual call, where two modems measure the line's own noise and frequency response before committing to a speed. There is no physical phone line here to measure, so this stage is texture, not a conformant negotiation - the one stage on this page that is not a faithful reconstruction." },
];

const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

const terminalOutput = document.getElementById('terminal-output');
const nowPlaying = document.getElementById('now-playing');
const dialBtn = document.getElementById('dial-btn');
const modeSelect = document.getElementById('mode-select');
const modeOneBtn = document.getElementById('mode-one-btn');
const modeTwoBtn = document.getElementById('mode-two-btn');
const micDiagnostic = document.getElementById('mic-diagnostic');
const endpointPanel = document.getElementById('endpoint-panel');
const endpointStatus = document.getElementById('endpoint-status');
const dialDigits = document.getElementById('dial-digits');
const endpointDialBtn = document.getElementById('endpoint-dial');
const endpointAnswerBtn = document.getElementById('endpoint-answer');
const endpointHangupBtn = document.getElementById('endpoint-hangup');
const endpointStopBtn = document.getElementById('endpoint-stop');
const chatInput = document.getElementById('chat-input');
const chatSendBtn = document.getElementById('chat-send');
const chatLog = document.getElementById('chat-log');
const canvas = document.getElementById('waterfall');
const phaseListEl = document.getElementById('phase-list');

const wiredPanel = document.getElementById('wired-panel');
const wiredPhase = document.getElementById('wired-phase');
const wiredStatusA = document.getElementById('wired-status-a');
const wiredStatusB = document.getElementById('wired-status-b');
const wiredLogA = document.getElementById('wired-log-a');
const wiredLogB = document.getElementById('wired-log-b');
const wiredCanvas = document.getElementById('wired-waterfall');
const wiredDigits = document.getElementById('wired-digits');
const wiredDialBtn = document.getElementById('wired-dial');
const wiredHangupBtn = document.getElementById('wired-hangup');
const wiredStopBtn = document.getElementById('wired-stop');
const wiredSendSide = document.getElementById('wired-send-side');
const wiredChat = document.getElementById('wired-chat');
const wiredSendBtn = document.getElementById('wired-send');

function appendTerminalLine(container, text, { command = false } = {}) {
  const line = document.createElement('p');
  line.className = 'terminal-line' + (command ? ' terminal-line--command terminal-line--reveal' : ' terminal-line--phase');
  line.textContent = text;
  container.appendChild(line);
  container.scrollTop = container.scrollHeight;
  return line;
}

// -----------------------------------------------------------------------
// The waterfall: frequency up the axis (300-3400 Hz, the whole telephone
// band), time across, newest column at the right - same layout modem-tui's
// own renderer uses, so a visitor recognises this when they later run the
// binary (see brand/README.md and the design spec's "Components" table).
//
// Phosphor decay is read from the brand token, never a fresh guess here -
// the same rule modem-tui/src/waterfall.rs follows for its own decay, and
// for the same reason: it is the strongest CRT cue there is, and the two
// surfaces have to agree on it or they read as different products. Each
// frame the whole canvas is faded by `1 - exp(-dt / decaySeconds)` before
// the new column is drawn, which is the continuous-time form of the same
// exponential the TUI applies per scrolled column.
// -----------------------------------------------------------------------
class Waterfall {
  constructor(canvasEl) {
    this.ctx = canvasEl.getContext('2d');
    this.width = canvasEl.width;
    this.height = canvasEl.height;
    const decayCss = getComputedStyle(document.documentElement).getPropertyValue('--modem-phosphor-decay').trim();
    this.decaySeconds = parseFloat(decayCss) || 2.56;
    const groundCss = getComputedStyle(document.documentElement).getPropertyValue('--modem-ground').trim();
    const greenCss = getComputedStyle(document.documentElement).getPropertyValue('--modem-green-bright').trim();
    this.ground = hexToRgb(groundCss);
    this.bright = hexToRgb(greenCss);
    this.lastFrame = null;
    this.floorDb = -70;
    this.ctx.fillStyle = groundCss;
    this.ctx.fillRect(0, 0, this.width, this.height);
  }

  frame(analyser, sampleRate) {
    const now = performance.now();
    const dt = this.lastFrame === null ? 1 / 60 : (now - this.lastFrame) / 1000;
    this.lastFrame = now;

    const fadeAlpha = 1 - Math.exp(-dt / this.decaySeconds);
    this.ctx.fillStyle = `rgba(${this.ground.r}, ${this.ground.g}, ${this.ground.b}, ${fadeAlpha})`;
    this.ctx.fillRect(0, 0, this.width, this.height);

    // Shift everything one column left, then draw the new column at the
    // right edge - the scrolling half of the effect.
    this.ctx.drawImage(this.ctx.canvas, -1, 0);

    const bins = new Float32Array(analyser.frequencyBinCount);
    analyser.getFloatFrequencyData(bins);
    const hzPerBin = sampleRate / analyser.fftSize;

    for (let y = 0; y < this.height; y++) {
      const freq = 3400 - (y / this.height) * (3400 - 300);
      const bin = Math.min(bins.length - 1, Math.max(0, Math.round(freq / hzPerBin)));
      const db = bins[bin];
      const t = Math.min(1, Math.max(0, (db - this.floorDb) / (0 - this.floorDb)));
      const r = lerp(this.ground.r, this.bright.r, t);
      const g = lerp(this.ground.g, this.bright.g, t);
      const b = lerp(this.ground.b, this.bright.b, t);
      this.ctx.fillStyle = `rgb(${r}, ${g}, ${b})`;
      this.ctx.fillRect(this.width - 1, y, 1, 1);
    }
  }

  reset() {
    this.lastFrame = null;
    this.ctx.fillStyle = `rgb(${this.ground.r}, ${this.ground.g}, ${this.ground.b})`;
    this.ctx.fillRect(0, 0, this.width, this.height);
  }
}

function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return { r: parseInt(h.slice(0, 2), 16), g: parseInt(h.slice(2, 4), 16), b: parseInt(h.slice(4, 6), 16) };
}

function lerp(a, b, t) {
  return Math.round(a + (b - a) * t);
}

const waterfall = new Waterfall(canvas);
// The "one device" live demo's own waterfall, driven off WiredEndpoint's
// analyser tap (see wired.js's own doc on why that tap exists) rather
// than the prerendered buffer this one reads from - the wired call is
// live audio with no buffer to slice. Kept as a second Waterfall
// instance, not a shared one: the two demos can be mid-animation at
// once (nothing stops a visitor opening "one device" without having
// pressed Dial first), and each owns its own canvas and fade state.
const wiredWaterfall = new Waterfall(wiredCanvas);
let wiredWaterfallRaf = null;

function startWiredWaterfall(endpoint) {
  stopWiredWaterfall();
  const draw = () => {
    try {
      wiredWaterfall.frame(endpoint.analyser, endpoint.ctx.sampleRate);
    } catch (err) {
      console.error('wired waterfall draw failed', err);
      return;
    }
    wiredWaterfallRaf = requestAnimationFrame(draw);
  };
  wiredWaterfallRaf = requestAnimationFrame(draw);
}

function stopWiredWaterfall() {
  if (wiredWaterfallRaf !== null) {
    cancelAnimationFrame(wiredWaterfallRaf);
    wiredWaterfallRaf = null;
  }
  wiredWaterfall.reset();
}

// -----------------------------------------------------------------------
// Prerendering the overture: the same modem-wasm build the real endpoint
// uses, run once on the main thread (no AudioWorklet needed for this -
// nothing here is on a real-time deadline) to render the whole
// performance into one buffer, segmented by the stage that owns each
// sample. Playing back a slice of that one real rendering is what makes
// "each phase individually playable" actually play the genuine DSP
// output rather than a second, hand-rolled tone generator that could
// drift from it.
// -----------------------------------------------------------------------
let audioCtx = null;
let prerenderPromise = null;

function ensureAudioContext() {
  if (!audioCtx) {
    audioCtx = new AudioContext();
  }
  if (audioCtx.state === 'suspended') {
    audioCtx.resume();
  }
  return audioCtx;
}

async function prerenderOverture(ctx) {
  const sampleRate = 8000; // modem-core's own internal rate - no resampling
  const response = await fetch('modem.wasm');
  const bytes = await response.arrayBuffer();
  const exportsHandle = await instantiateModemModule(bytes);
  const session = new SessionHandle(exportsHandle, { sampleRate, role: Role.ORIGINATE, duplex: Duplex.HALF_PING_PONG });
  // SessionHandle.dial wants raw bytes, not a string - ModemEndpoint.dial
  // (modem.js) does this same encode() call for its callers; this is the
  // same low-level SessionHandle those callers sit on top of.
  session.dial(new TextEncoder().encode('01234567890'));

  const BLOCK = 256;
  const CONNECTED_TAIL_S = 1.2; // enough to hear CONNECT 300 land, no longer
  const SAFETY_CAP_S = 20; // the overture's own documented upper bound

  const chunks = [];
  const segments = [];
  let cursor = 0;
  let current = null;
  let connectedAt = null;
  const buf = new Float32Array(BLOCK);

  for (;;) {
    session.processOut(buf);
    chunks.push(buf.slice());
    const state = session.state();
    const stage = session.stage();
    const label = state === SessionState.CONNECTED ? 'connected' : stage;

    if (current === null || current.label !== label) {
      if (current) current.endSample = cursor;
      current = { label, startSample: cursor, endSample: null };
      segments.push(current);
    }
    cursor += BLOCK;

    if (state === SessionState.CONNECTED) {
      if (connectedAt === null) connectedAt = cursor;
      if ((cursor - connectedAt) / sampleRate >= CONNECTED_TAIL_S) break;
    }
    if (cursor / sampleRate > SAFETY_CAP_S) break;
  }
  current.endSample = cursor;
  session.free();

  const master = new Float32Array(cursor);
  let offset = 0;
  for (const chunk of chunks) {
    master.set(chunk, offset);
    offset += chunk.length;
  }

  const audioBuffer = ctx.createBuffer(1, master.length, sampleRate);
  audioBuffer.copyToChannel(master, 0);

  const stageSegments = new Map();
  for (const seg of segments) {
    if (typeof seg.label === 'number') stageSegments.set(seg.label, seg);
  }

  return { audioBuffer, segments, stageSegments, sampleRate };
}

function ensurePrerendered() {
  const ctx = ensureAudioContext();
  if (!prerenderPromise) {
    prerenderPromise = prerenderOverture(ctx);
  }
  return prerenderPromise;
}

let activeTimers = [];
function clearScheduledAnnotations() {
  for (const t of activeTimers) clearTimeout(t);
  activeTimers = [];
}

function labelText(label) {
  return label === 'connected' ? 'CONNECT 300' : STAGE_NAMES[label];
}

function setActivePhaseRow(label) {
  const rows = phaseListEl.querySelectorAll('.phase-row');
  rows.forEach((row) => row.classList.remove('phase-row--active'));
  if (typeof label === 'number') {
    const row = phaseListEl.querySelector(`[data-stage="${label}"]`);
    if (row) row.classList.add('phase-row--active');
  }
}

// -----------------------------------------------------------------------
// Exactly one clip plays at a time - the Dial button's full overture and
// every phase-row's own slice all go through `playSlice`, and starting
// any one of them stops whatever else was running first. Before this,
// each phase button only disabled itself, so two phases (or a phase and
// the full overture) could play over each other, both painting the one
// waterfall and both talking over the same speakers.
// -----------------------------------------------------------------------
let currentPlayback = null;

function stopCurrentPlayback() {
  if (currentPlayback) {
    const playing = currentPlayback;
    currentPlayback = null;
    playing.stop();
  }
}

/** Plays `[startSample, endSample)` of the prerendered buffer through the
 * waterfall's analyser, resolving once playback ends (naturally, or via
 * `stopCurrentPlayback`). Pre-empts whatever else was already playing. */
function playSlice({ audioBuffer, sampleRate }, startSample, endSample) {
  stopCurrentPlayback();

  const ctx = ensureAudioContext();
  const analyser = ctx.createAnalyser();
  analyser.fftSize = 2048;
  const source = ctx.createBufferSource();
  source.buffer = audioBuffer;
  source.connect(analyser);
  analyser.connect(ctx.destination);

  let raf = null;
  const draw = () => {
    waterfall.frame(analyser, ctx.sampleRate);
    raf = requestAnimationFrame(draw);
  };
  raf = requestAnimationFrame(draw);

  const offset = startSample / sampleRate;
  const duration = (endSample - startSample) / sampleRate;
  source.start(0, offset, duration);

  const token = {
    stop() {
      try {
        source.stop();
      } catch (_err) {
        // Already stopped or never started - nothing left to do.
      }
    },
  };
  currentPlayback = token;

  return new Promise((resolve) => {
    source.onended = () => {
      cancelAnimationFrame(raf);
      if (currentPlayback === token) currentPlayback = null;
      resolve();
    };
  });
}

async function playFullOverture() {
  dialBtn.disabled = true;
  resetAllPhaseButtons();
  nowPlaying.textContent = 'Loading...';
  terminalOutput.innerHTML = '';
  waterfall.reset();

  const rendered = await ensurePrerendered();
  appendTerminalLine(terminalOutput, 'ATDT01234567890', { command: true });

  clearScheduledAnnotations();
  for (const seg of rendered.segments) {
    const atMs = (seg.startSample / rendered.sampleRate) * 1000;
    activeTimers.push(setTimeout(() => {
      nowPlaying.textContent = labelText(seg.label);
      setActivePhaseRow(seg.label);
      if (seg.label === 'connected') {
        appendTerminalLine(terminalOutput, 'CONNECT 300', { command: true });
      } else {
        appendTerminalLine(terminalOutput, STAGE_NAMES[seg.label]);
      }
    }, atMs));
  }

  await playSlice(rendered, 0, rendered.segments[rendered.segments.length - 1].endSample);

  clearScheduledAnnotations();
  nowPlaying.textContent = 'Idle';
  setActivePhaseRow(null);
  dialBtn.disabled = false;
  modeSelect.hidden = false;
}

dialBtn.addEventListener('click', () => {
  playFullOverture().catch((err) => {
    console.error(err);
    nowPlaying.textContent = 'Playback failed - see the console';
    dialBtn.disabled = false;
  });
});

// -----------------------------------------------------------------------
// The explainer: one phase-row per stage, each playing its own slice of
// the identical rendering the dial button uses. Exactly one plays at a
// time (see `currentPlayback` above) - clicking a row's button while it
// is the one playing stops it early; clicking a different row's button
// switches to that clip instead of layering on top of the first.
// -----------------------------------------------------------------------
let activePhaseIndex = null;

function resetAllPhaseButtons() {
  phaseListEl.querySelectorAll('.phase-row__play').forEach((b) => {
    b.textContent = 'Play';
  });
  activePhaseIndex = null;
}

PHASES.forEach((phase, index) => {
  const li = document.createElement('li');
  li.className = 'phase-row';
  li.dataset.stage = String(index);

  const button = document.createElement('button');
  button.type = 'button';
  button.className = 'phase-row__play';
  button.textContent = 'Play';
  button.addEventListener('click', async () => {
    if (activePhaseIndex === index) {
      // Already the one playing - a second click stops it, and does not
      // start anything new.
      stopCurrentPlayback();
      return;
    }

    resetAllPhaseButtons();
    activePhaseIndex = index;
    button.textContent = 'Stop';
    try {
      const rendered = await ensurePrerendered();
      const seg = rendered.stageSegments.get(index);
      if (!seg) throw new Error(`stage ${index} did not appear in the rendered overture`);
      nowPlaying.textContent = STAGE_NAMES[index];
      setActivePhaseRow(index);
      await playSlice(rendered, seg.startSample, seg.endSample);
    } catch (err) {
      console.error(err);
    } finally {
      // Guards against a preempted clip's own cleanup running after a
      // newer one has already taken over - see playSlice's token
      // handling, which is the other half of this same guard.
      if (activePhaseIndex === index) {
        nowPlaying.textContent = 'Idle';
        setActivePhaseRow(null);
        button.textContent = 'Play';
        activePhaseIndex = null;
      }
    }
  });

  const body = document.createElement('div');
  body.className = 'phase-row__body';
  const h3 = document.createElement('h3');
  h3.className = 'phase-row__label';
  h3.textContent = phase.label;
  const p = document.createElement('p');
  p.className = 'phase-row__description';
  p.textContent = phase.description;
  body.appendChild(h3);
  body.appendChild(p);

  li.appendChild(button);
  li.appendChild(body);
  phaseListEl.appendChild(li);
});

// -----------------------------------------------------------------------
// The live demos - offered only once the passive overture has played,
// per the staged design: front-loading a mode choice (let alone a
// microphone prompt) loses a visitor who has no idea yet what this site
// is. Two modes, matching the binary's own two ways to run it (see the
// "Two ways to try this" section below): "One device" cross-wires two
// real Sessions in software, right here in the page, exactly as
// modem-audio's WiredTransport does; "Two devices" turns this tab into
// one real endpoint, listening on a raw microphone, that a copy of the
// binary on a second machine can dial or answer.
// -----------------------------------------------------------------------
let endpoint = null;

function endpointStateName(state) {
  switch (state) {
    case SessionState.IDLE: return 'IDLE';
    case SessionState.DIALLING: return 'DIALLING';
    case SessionState.ANSWERING: return 'ANSWERING';
    case SessionState.CONNECTED: return 'CONNECTED';
    default: return String(state);
  }
}

modeTwoBtn.addEventListener('click', async () => {
  modeOneBtn.disabled = true;
  modeTwoBtn.disabled = true;
  micDiagnostic.textContent = 'Requesting the endpoint and microphone...';
  micDiagnostic.className = 'diagnostic';
  try {
    endpoint = new ModemEndpoint();
    await endpoint.init({ role: Role.ORIGINATE, duplex: Duplex.HALF_PING_PONG });

    endpoint.addEventListener('status', (e) => {
      const { state, stage, hasTurn, carrier } = e.detail;
      const stageName = typeof stage === 'number' && stage >= 0 ? STAGE_NAMES[stage] : 'none';
      endpointStatus.textContent = `${endpointStateName(state)} - stage: ${stageName} - turn: ${hasTurn ? 'yours' : 'not yours'} - carrier: ${carrier ? 'yes' : 'no'}`;
      const connected = state === SessionState.CONNECTED;
      chatInput.disabled = !connected;
      chatSendBtn.disabled = !connected;
      endpointHangupBtn.disabled = state === SessionState.IDLE;
    });

    endpoint.addEventListener('data', (e) => {
      const text = new TextDecoder().decode(e.detail);
      appendTerminalLine(chatLog, text);
    });

    endpoint.addEventListener('error', (e) => {
      appendTerminalLine(chatLog, `error: ${e.detail}`);
    });

    const diagnostics = await endpoint.openMicrophone();
    const summary = summariseMicDiagnostics(diagnostics);
    micDiagnostic.textContent = summary;
    micDiagnostic.className = diagnostics.warnings.length > 0 ? 'diagnostic diagnostic--warning' : 'diagnostic';

    endpointPanel.hidden = false;
    modeSelect.hidden = true;
  } catch (err) {
    console.error(err);
    micDiagnostic.textContent = `Could not open the endpoint: ${err.message || err}`;
    micDiagnostic.className = 'diagnostic diagnostic--warning';
    modeOneBtn.disabled = false;
    modeTwoBtn.disabled = false;
  }
});

endpointDialBtn.addEventListener('click', () => {
  if (!endpoint) return;
  endpoint.dial(dialDigits.value || '0');
  endpointHangupBtn.disabled = false;
});

endpointAnswerBtn.addEventListener('click', () => {
  if (!endpoint) return;
  endpoint.answer();
  endpointHangupBtn.disabled = false;
});

endpointHangupBtn.addEventListener('click', () => {
  if (!endpoint) return;
  endpoint.hangup();
});

// The one control that fully releases the microphone rather than just
// ending a call - spike/README.md finding 5's rule applies to more than
// a forgotten carrier: a visitor should never have to close the tab to
// know their microphone is off. Restores the page to its pre-connect
// state so "Two devices" can be chosen again.
endpointStopBtn.addEventListener('click', async () => {
  if (!endpoint) return;
  await endpoint.stop();
  endpoint = null;
  endpointPanel.hidden = true;
  chatLog.innerHTML = '';
  endpointStatus.textContent = 'IDLE';
  micDiagnostic.textContent = 'Microphone disconnected';
  micDiagnostic.className = 'diagnostic';
  modeSelect.hidden = false;
  modeOneBtn.disabled = false;
  modeTwoBtn.disabled = false;
});

chatSendBtn.addEventListener('click', () => {
  if (!endpoint || !chatInput.value) return;
  endpoint.send(chatInput.value);
  appendTerminalLine(chatLog, `> ${chatInput.value}`);
  chatInput.value = '';
});

chatInput.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') chatSendBtn.click();
});

// -----------------------------------------------------------------------
// "One device" - two real Sessions cross-wired in software, right here
// in the page, the browser mirror of modem-audio/src/transport.rs's
// WiredTransport. No microphone and no permission prompt: both ends
// live in this page and the mixed signal plays through the visitor's
// own speakers.
//
// Answer auto-answers, matching the binary: `modem --single --acoustic
// --answer` answers at startup with nothing typed into it (see
// modem-tui/src/app.rs's own module doc, "--answer picks receive mode,
// and that end answers by itself"). There is no separate "ATA (answer)"
// control here any more - `wired.answer()` is called as soon as the
// session pair exists, before the panel is even shown, the same "nothing
// to type on it" shape as a real answer-mode end sitting ready.
// -----------------------------------------------------------------------
let wired = null;
let lastWiredA = null;
let lastWiredB = null;

/** One word for a panel's own status line - the long combined string
 * (state/stage/turn/carrier) now lives only in the shared phase line
 * below, so the two are not saying almost the same thing twice. */
function wiredShortStatus(status) {
  return endpointStateName(status.state);
}

/** The call's overall phase, shared above both panels rather than
 * repeated inside each - "both ends live" is one story, not two. */
function wiredPhaseLine(a, b) {
  if (a.state === SessionState.CONNECTED && b.state === SessionState.CONNECTED) {
    return 'CONNECTED';
  }
  // Answer auto-answers as soon as the pair exists (see this section's
  // own doc), so it can be ANSWERING well before anyone has dialled -
  // the call itself has not started until originate has, regardless of
  // what state answer is already sitting in.
  if (a.state === SessionState.IDLE) {
    return 'IDLE - press ATDT to dial';
  }
  const stage = typeof a.stage === 'number' && a.stage >= 0 ? a.stage
    : typeof b.stage === 'number' && b.stage >= 0 ? b.stage
    : null;
  const stageName = stage !== null ? STAGE_NAMES[stage] : 'connecting';
  return `Handshake: ${stageName}`;
}

function updateWiredComposerEnablement() {
  const bothConnected = !!lastWiredA && !!lastWiredB
    && lastWiredA.state === SessionState.CONNECTED
    && lastWiredB.state === SessionState.CONNECTED;
  wiredChat.disabled = !bothConnected;
  wiredSendBtn.disabled = !bothConnected;
}

modeOneBtn.addEventListener('click', async () => {
  modeOneBtn.disabled = true;
  modeTwoBtn.disabled = true;
  try {
    wired = new WiredEndpoint();
    await wired.init({ duplex: Duplex.HALF_PING_PONG });

    wired.addEventListener('status', (e) => {
      const { a, b } = e.detail;
      lastWiredA = a;
      lastWiredB = b;
      wiredStatusA.textContent = wiredShortStatus(a);
      wiredStatusB.textContent = wiredShortStatus(b);
      wiredPhase.textContent = wiredPhaseLine(a, b);
      updateWiredComposerEnablement();
      wiredHangupBtn.disabled = a.state === SessionState.IDLE && b.state === SessionState.IDLE;
    });

    wired.addEventListener('data', (e) => {
      const { side, bytes } = e.detail;
      appendTerminalLine(side === 'a' ? wiredLogA : wiredLogB, decodeWired(bytes));
    });

    wired.addEventListener('error', (e) => {
      appendTerminalLine(wiredLogA, `error: ${e.detail}`);
    });

    // Auto-answer - see this section's own doc above.
    wired.answer();

    startWiredWaterfall(wired);
    wiredPanel.hidden = false;
    modeSelect.hidden = true;
  } catch (err) {
    console.error(err);
    micDiagnostic.textContent = `Could not start the one-device demo: ${err.message || err}`;
    micDiagnostic.className = 'diagnostic diagnostic--warning';
    modeOneBtn.disabled = false;
    modeTwoBtn.disabled = false;
  }
});

wiredDialBtn.addEventListener('click', () => {
  if (!wired) return;
  const digits = wiredDigits.value || '0';
  wired.dial(digits);
  appendTerminalLine(wiredLogA, `ATDT${digits}`, { command: true });
});

wiredHangupBtn.addEventListener('click', () => {
  if (!wired) return;
  wired.hangup();
});

// Fully releases the audio graph rather than relying on hangup() alone -
// see wired.js's own stop() doc: an idle Session outputs silence, but
// the node itself keeps rendering it until the context closes. Restores
// the page to its pre-connect state so a mode can be chosen again.
wiredStopBtn.addEventListener('click', async () => {
  if (!wired) return;
  await wired.stop();
  wired = null;
  lastWiredA = null;
  lastWiredB = null;
  stopWiredWaterfall();
  wiredPanel.hidden = true;
  wiredLogA.innerHTML = '';
  wiredLogB.innerHTML = '';
  wiredStatusA.textContent = 'IDLE';
  wiredStatusB.textContent = 'IDLE';
  wiredPhase.textContent = 'IDLE - press ATDT to dial';
  updateWiredComposerEnablement();
  modeSelect.hidden = false;
  modeOneBtn.disabled = false;
  modeTwoBtn.disabled = false;
});

wiredSendBtn.addEventListener('click', () => {
  if (!wired || !wiredChat.value) return;
  const side = wiredSendSide.value === 'b' ? 'b' : 'a';
  wired.send(side, wiredChat.value);
  appendTerminalLine(side === 'a' ? wiredLogA : wiredLogB, `> ${wiredChat.value}`);
  wiredChat.value = '';
});

wiredChat.addEventListener('keydown', (e) => {
  if (e.key === 'Enter') wiredSendBtn.click();
});

// A page navigating away must not leave a live microphone, a live wired
// call, or a carrier running - see spike/README.md finding 5 and both
// endpoints' own `stop()` docs. Best-effort: `beforeunload` cannot
// await, but stop() only tears down local objects (tracks, node,
// context), none of which need a network round trip.
window.addEventListener('beforeunload', () => {
  if (endpoint) endpoint.stop();
  if (wired) wired.stop();
});
